const cards = [
  [
    {
      id: 1,
      title: 'Action (set A)',
      src: 'assets/images/cry.jpg',
    },
    {
      id: 2,
      title: 'Action (set B)',
      src: 'assets/images/dance.jpg',
    },
    {
      id: 3,
      title: 'Action (set C)',
      src: 'assets/images/wash.jpg',
    },
    {
      id: 4,
      title: 'Action (set D)',
      src: 'assets/images/dig.jpg',
    },
    {
      id: 5,
      title: 'Animal (set A)',
      src: 'assets/images/cat.jpg',
    },
    {
      id: 6,
      title: 'Animal (set B)',
      src: 'assets/images/dog.jpg',
    },
    {
      id: 7,
      title: 'Emotions',
      src: 'assets/images/happy.jpg',
    },
    {
      id: 8,
      title: 'Clothes',
      src: 'assets/images/blouse.jpg',
    },
  ],
  [
    {
      category: 'Action A',
      word: 'cry',
      translation: 'плакать',
      image: 'assets/images/cry.jpg',
      audioSrc: 'audio/cry.mp3',
    },
    {
      category: 'Action A',
      word: 'dance',
      translation: 'танцевать',
      image: 'assets/images/dance.jpg',
      audioSrc: 'audio/dance.mp3',
    },
    {
      category: 'Action A',
      word: 'dive',
      translation: 'нырять',
      image: 'assets/images/dive.jpg',
      audioSrc: 'audio/dive.mp3',
    },
    {
      category: 'Action A',
      word: 'draw',
      translation: 'рисовать',
      image: 'assets/images/draw.jpg',
      audioSrc: 'audio/draw.mp3',
    },
    {
      category: 'Action A',
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'assets/images/fish.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      category: 'Action A',
      word: 'fly',
      translation: 'летать',
      image: 'assets/images/fly.jpg',
      audioSrc: 'audio/fly.mp3',
    },
    {
      category: 'Action A',
      word: 'hug',
      translation: 'обнимать',
      image: 'assets/images/hug.jpg',
      audioSrc: 'audio/hug.mp3',
    },
    {
      category: 'Action A',
      word: 'jump',
      translation: 'прыгать',
      image: 'assets/images/jump.jpg',
      audioSrc: 'audio/jump.mp3',
    },
  ],
  [
    {
      category: 'Action B',
      word: 'open',
      translation: 'открывать',
      image: 'assets/images/open.jpg',
      audioSrc: 'audio/open.mp3',
    },
    {
      category: 'Action B',
      word: 'play',
      translation: 'играть',
      image: 'assets/images/play.jpg',
      audioSrc: 'audio/play.mp3',
    },
    {
      category: 'Action B',
      word: 'point',
      translation: 'указывать',
      image: 'assets/images/point.jpg',
      audioSrc: 'audio/point.mp3',
    },
    {
      category: 'Action B',
      word: 'ride',
      translation: 'ездить',
      image: 'assets/images/ride.jpg',
      audioSrc: 'audio/ride.mp3',
    },
    {
      category: 'Action B',
      word: 'run',
      translation: 'бегать',
      image: 'assets/images/run.jpg',
      audioSrc: 'audio/run.mp3',
    },
    {
      category: 'Action B',
      word: 'sing',
      translation: 'петь',
      image: 'assets/images/sing.jpg',
      audioSrc: 'audio/sing.mp3',
    },
    {
      category: 'Action B',
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'assets/images/skip.jpg',
      audioSrc: 'audio/skip.mp3',
    },
    {
      category: 'Action B',
      word: 'swim',
      translation: 'плавать',
      image: 'assets/images/swim.jpg',
      audioSrc: 'audio/swim.mp3',
    },
  ],
  [
    {
      category: 'Action C',
      word: 'buy',
      translation: 'покупать',
      image: 'assets/images/buy.jpg',
      audioSrc: 'audio/buy.mp3',
    },
    {
      category: 'Action C',
      word: 'climb',
      translation: 'Подниматься',
      image: 'assets/images/climb.jpg',
      audioSrc: 'audio/climb.mp3',
    },
    {
      category: 'Action C',
      word: 'cook',
      translation: 'готовить',
      image: 'assets/images/cook.jpg',
      audioSrc: 'audio/cook.mp3',
    },
    {
      category: 'Action C',
      word: 'dig',
      translation: 'копать',
      image: 'assets/images/dig.jpg',
      audioSrc: 'audio/dig.mp3',
    },
    {
      category: 'Action C',
      word: 'dream',
      translation: 'мечтать',
      image: 'assets/images/dream.jpg',
      audioSrc: 'audio/dream.mp3',
    },
    {
      category: 'Action C',
      word: 'eat',
      translation: 'есть',
      image: 'assets/images/eat.jpg',
      audioSrc: 'audio/eat.mp3',
    },
    {
      category: 'Action C',
      word: 'hunt',
      translation: 'охотиться',
      image: 'assets/images/hunt.jpg',
      audioSrc: 'audio/hunt.mp3',
    },
    {
      category: 'Action C',
      word: 'knit',
      translation: 'вязать',
      image: 'assets/images/knit.jpg',
      audioSrc: 'audio/knit.mp3',
    },
  ],
  [
    {
      category: 'Action D',
      word: 'read',
      translation: 'читать',
      image: 'assets/images/read.jpg',
      audioSrc: 'audio/read.mp3',
    },
    {
      category: 'Action D',
      word: 'repair',
      translation: 'ремонтировать',
      image: 'assets/images/repair.jpg',
      audioSrc: 'audio/repair.mp3',
    },
    {
      category: 'Action D',
      word: 'shake',
      translation: 'трясти',
      image: 'assets/images/shake.jpg',
      audioSrc: 'audio/shake.mp3',
    },
    {
      category: 'Action D',
      word: 'ski',
      translation: 'кататься',
      image: 'assets/images/ski.jpg',
      audioSrc: 'audio/ski.mp3',
    },
    {
      category: 'Action D',
      word: 'sleep',
      translation: 'спать',
      image: 'assets/images/sleep.jpg',
      audioSrc: 'audio/sleep.mp3',
    },
    {
      category: 'Action D',
      word: 'talk',
      translation: 'разговаривать',
      image: 'assets/images/talk.jpg',
      audioSrc: 'audio/talk.mp3',
    },
    {
      category: 'Action D',
      word: 'wait',
      translation: 'ждать',
      image: 'assets/images/wait.jpg',
      audioSrc: 'audio/wait.mp3',
    },
    {
      category: 'Action D',
      word: 'wash',
      translation: 'мыть',
      image: 'assets/images/wash.jpg',
      audioSrc: 'audio/wash.mp3',
    },
  ],
  [
    {
      category: 'Animal A',
      word: 'cat',
      translation: 'кот',
      image: 'assets/images/cat.jpg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      category: 'Animal A',
      word: 'chick',
      translation: 'цыплёнок',
      image: 'assets/images/chick.jpg',
      audioSrc: 'audio/chick.mp3',
    },
    {
      category: 'Animal A',
      word: 'chicken',
      translation: 'курица',
      image: 'assets/images/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
    },
    {
      category: 'Animal A',
      word: 'dog',
      translation: 'собака',
      image: 'assets/images/dog.jpg',
      audioSrc: 'audio/dog.mp3',
    },
    {
      category: 'Animal A',
      word: 'horse',
      translation: 'лошадь',
      image: 'assets/images/horse.jpg',
      audioSrc: 'audio/horse.mp3',
    },
    {
      category: 'Animal A',
      word: 'pig',
      translation: 'свинья',
      image: 'assets/images/pig.jpg',
      audioSrc: 'audio/pig.mp3',
    },
    {
      category: 'Animal A',
      word: 'rabbit',
      translation: 'кролик',
      image: 'assets/images/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
    },
    {
      category: 'Animal A',
      word: 'sheep',
      translation: 'овца',
      image: 'assets/images/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
    },
  ],
  [
    {
      category: 'Animal B',
      word: 'bird',
      translation: 'птица',
      image: 'assets/images/bird.jpg',
      audioSrc: 'audio/bird.mp3',
    },
    {
      category: 'Animal B',
      word: 'fish',
      translation: 'рыба',
      image: 'assets/images/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      category: 'Animal B',
      word: 'frog',
      translation: 'жаба',
      image: 'assets/images/frog.jpg',
      audioSrc: 'audio/frog.mp3',
    },
    {
      category: 'Animal B',
      word: 'giraffe',
      translation: 'жирафа',
      image: 'assets/images/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
    },
    {
      category: 'Animal B',
      word: 'lion',
      translation: 'лев',
      image: 'assets/images/lion.jpg',
      audioSrc: 'audio/lion.mp3',
    },
    {
      category: 'Animal B',
      word: 'mouse',
      translation: 'мышь',
      image: 'assets/images/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
    },
    {
      category: 'Animal B',
      word: 'turtle',
      translation: 'черепаха',
      image: 'assets/images/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
    },
    {
      category: 'Animal B',
      word: 'dolphin',
      translation: 'дельфин',
      image: 'assets/images/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
    },
  ],
  [
    {
      category: 'Emotions',
      word: 'sad',
      translation: 'грустный',
      image: 'assets/images/sad.jpg',
      audioSrc: 'audio/sad.mp3',
    },
    {
      category: 'Emotions',
      word: 'angry',
      translation: 'сердитый',
      image: 'assets/images/angry.jpg',
      audioSrc: 'audio/angry.mp3',
    },
    {
      category: 'Emotions',
      word: 'happy',
      translation: 'счастливый',
      image: 'assets/images/happy.jpg',
      audioSrc: 'audio/happy.mp3',
    },
    {
      category: 'Emotions',
      word: 'tired',
      translation: 'уставший',
      image: 'assets/images/tired.jpg',
      audioSrc: 'audio/tired.mp3',
    },
    {
      category: 'Emotions',
      word: 'surprised',
      translation: 'удивлённый',
      image: 'assets/images/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
    },
    {
      category: 'Emotions',
      word: 'scared',
      translation: 'испуганный',
      image: 'assets/images/scared.jpg',
      audioSrc: 'audio/scared.mp3',
    },
    {
      category: 'Emotions',
      word: 'smile',
      translation: 'улыбка',
      image: 'assets/images/smile.jpg',
      audioSrc: 'audio/smile.mp3',
    },
    {
      category: 'Emotions',
      word: 'laugh',
      translation: 'смех',
      image: 'assets/images/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
    },
  ],
  [
    {
      category: 'Clothes',
      word: 'skirt',
      translation: 'юбка',
      image: 'assets/images/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
    },
    {
      category: 'Clothes',
      word: 'pants',
      translation: 'брюки',
      image: 'assets/images/pants.jpg',
      audioSrc: 'audio/pants.mp3',
    },
    {
      category: 'Clothes',
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/images/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
    },
    {
      category: 'Clothes',
      word: 'dress',
      translation: 'платье',
      image: 'assets/images/dress.jpg',
      audioSrc: 'audio/dress.mp3',
    },
    {
      category: 'Clothes',
      word: 'boot',
      translation: 'ботинок',
      image: 'assets/images/boot.jpg',
      audioSrc: 'audio/boot.mp3',
    },
    {
      category: 'Clothes',
      word: 'shirt',
      translation: 'рубашка',
      image: 'assets/images/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
    },
    {
      category: 'Clothes',
      word: 'coat',
      translation: 'пальто',
      image: 'assets/images/coat.jpg',
      audioSrc: 'audio/coat.mp3',
    },
    {
      category: 'Clothes',
      word: 'shoe',
      translation: 'туфли',
      image: 'assets/images/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
    },
  ],
];

export default cards;
